// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: app/src/main/jflex_jcup/lexer_pkm.jflex

package com.compi1.proyecto1.analizadores; // Cambia esto a tu paquete

import java_cup.runtime.*;
import com.compi1.proyecto1.utils.ManejadorErrores; // Reutilizamos tu caja de errores


@SuppressWarnings("fallthrough")
public class LexerPKM implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\37\u0200\1\u0300\u10de\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\4"+
    "\1\0\1\5\1\6\10\0\1\7\1\10\1\11\1\12"+
    "\12\13\1\14\1\0\1\15\1\16\1\17\1\0\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\20\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\20\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\4\0\1\51\1\0\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\20\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\20\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\52"+
    "\1\0\1\53\125\0\1\54\6\0\1\55\30\0\1\54"+
    "\6\0\1\55\65\0\2\56\115\0\1\57\u01aa\0\1\60"+
    "\325\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\2\1\1\3\1\1\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\21\4\1\12\1\13\1\1"+
    "\1\0\1\14\1\0\1\15\1\6\1\4\2\0\21\4"+
    "\1\0\3\4\1\0\13\4\3\0\1\16\1\0\1\6"+
    "\2\0\1\4\1\0\12\4\1\0\12\4\1\0\3\4"+
    "\1\0\1\4\1\17\11\4\1\0\1\4\4\0\1\6"+
    "\1\0\1\4\1\0\2\4\1\0\5\4\1\0\2\4"+
    "\2\0\2\4\1\20\5\4\1\0\2\21\1\4\1\22"+
    "\1\4\1\0\1\23\1\4\1\0\7\4\1\0\1\4"+
    "\5\0\1\4\1\0\2\4\1\0\1\17\1\4\1\24"+
    "\2\4\1\0\2\4\2\0\3\4\1\0\1\25\1\4"+
    "\1\0\2\4\2\0\1\4\1\0\1\4\1\0\1\4"+
    "\1\26\1\27\1\0\2\4\1\0\1\4\1\0\1\26"+
    "\1\0\1\4\1\0\1\4\1\0\1\30\2\4\1\0"+
    "\1\4\1\0\1\4\1\0\1\31\1\32\1\4\1\0"+
    "\1\4\1\0\2\4\2\0\1\4\1\0\1\4\1\0"+
    "\1\4\1\33\2\0\1\4\2\0\1\33\1\0\1\34"+
    "\1\4\1\0\1\4\1\0\1\35\2\36\1\4\1\0"+
    "\1\4\1\0\1\37\1\0\1\4\1\0\1\4\2\0"+
    "\1\4\1\0\2\40\1\4\3\0\1\4\2\0\1\4"+
    "\1\0\1\4\1\0\1\4\2\0\1\4\1\0\2\41"+
    "\1\4\4\0\2\42\1\25\1\4\1\0\1\4\1\0"+
    "\1\4\1\0\1\4\1\0\1\4\1\0\1\43\1\0"+
    "\1\4\1\0\2\4\1\0\2\44\2\45\3\0\1\46"+
    "\15\0\1\47";

  private static int [] zzUnpackAction() {
    int [] result = new int[341];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\61\0\142\0\223\0\304\0\61\0\365"+
    "\0\u0126\0\u0126\0\u0157\0\u0188\0\61\0\61\0\u01b9\0\u01ea"+
    "\0\u021b\0\u024c\0\u027d\0\u02ae\0\u02df\0\u0310\0\u0341\0\u0372"+
    "\0\u03a3\0\u03d4\0\u0405\0\u0436\0\u0467\0\u0498\0\u04c9\0\61"+
    "\0\61\0\u04fa\0\223\0\61\0\u052b\0\u055c\0\u058d\0\u05be"+
    "\0\u0188\0\u05ef\0\u0620\0\u0651\0\u0682\0\u06b3\0\u06e4\0\u0715"+
    "\0\u0746\0\u0777\0\u07a8\0\u07d9\0\u080a\0\u083b\0\u086c\0\u089d"+
    "\0\u08ce\0\u08ff\0\u0930\0\u0961\0\u0992\0\u09c3\0\u09f4\0\u0a25"+
    "\0\u0a56\0\u0a87\0\u0ab8\0\u0ae9\0\u0b1a\0\u0b4b\0\u0b7c\0\u0bad"+
    "\0\u0bde\0\u0c0f\0\u0c40\0\u0c71\0\u0ca2\0\u0cd3\0\61\0\u0d04"+
    "\0\u05be\0\u0d35\0\u0d66\0\u0d97\0\u0dc8\0\u0df9\0\u0e2a\0\u0e5b"+
    "\0\u0e8c\0\u0ebd\0\u0eee\0\u0f1f\0\u0f50\0\u0f81\0\u0fb2\0\u0fe3"+
    "\0\u1014\0\u1045\0\u1076\0\u10a7\0\u10d8\0\u1109\0\u113a\0\u116b"+
    "\0\u119c\0\u11cd\0\u11fe\0\u122f\0\u1260\0\u1291\0\u12c2\0\u12f3"+
    "\0\u0126\0\u1324\0\u1355\0\u1386\0\u13b7\0\u13e8\0\u1419\0\u144a"+
    "\0\u147b\0\u14ac\0\u14dd\0\u150e\0\u153f\0\u1570\0\u15a1\0\u15d2"+
    "\0\u0d04\0\u1603\0\u1634\0\u1665\0\u1696\0\u16c7\0\u16f8\0\u1729"+
    "\0\u175a\0\u178b\0\u17bc\0\u17ed\0\u181e\0\u184f\0\u1880\0\u18b1"+
    "\0\u18e2\0\u1913\0\u1944\0\u0126\0\u1975\0\u19a6\0\u19d7\0\u1a08"+
    "\0\u1a39\0\u1a6a\0\u0126\0\61\0\u1a9b\0\u0126\0\u1acc\0\u1afd"+
    "\0\u0126\0\u1b2e\0\u1b5f\0\u1b90\0\u1bc1\0\u1bf2\0\u1c23\0\u1c54"+
    "\0\u1c85\0\u1cb6\0\u1ce7\0\u1d18\0\u1d49\0\u1d7a\0\u1dab\0\u1ddc"+
    "\0\u1e0d\0\u1e3e\0\u1e6f\0\u1ea0\0\u1ed1\0\u1f02\0\61\0\u1f33"+
    "\0\u0126\0\u1f64\0\u1f95\0\u1fc6\0\u1ff7\0\u2028\0\u2059\0\u208a"+
    "\0\u20bb\0\u20ec\0\u211d\0\u214e\0\u0126\0\u217f\0\u21b0\0\u21e1"+
    "\0\u2212\0\u2243\0\u2274\0\u22a5\0\u22d6\0\u2307\0\u2338\0\u2369"+
    "\0\u0126\0\u0126\0\u239a\0\u23cb\0\u23fc\0\u242d\0\u245e\0\u248f"+
    "\0\61\0\u24c0\0\u24f1\0\u2522\0\u2553\0\u2584\0\u0126\0\u25b5"+
    "\0\u25e6\0\u2617\0\u2648\0\u2679\0\u26aa\0\u26db\0\u0126\0\u0126"+
    "\0\u270c\0\u273d\0\u276e\0\u279f\0\u27d0\0\u2801\0\u2832\0\u2863"+
    "\0\u2894\0\u28c5\0\u28f6\0\u2927\0\u2958\0\u0126\0\u2989\0\u29ba"+
    "\0\u29eb\0\u2a1c\0\u2a4d\0\61\0\u2a7e\0\61\0\u2aaf\0\u2ae0"+
    "\0\u2b11\0\u2b42\0\u0126\0\u0126\0\61\0\u2b73\0\u2ba4\0\u2bd5"+
    "\0\u2c06\0\u0126\0\u2c37\0\u2c68\0\u2c99\0\u2cca\0\u2cfb\0\u2d2c"+
    "\0\u2d5d\0\u2d8e\0\u0126\0\61\0\u2dbf\0\u2df0\0\u2e21\0\u2e52"+
    "\0\u2e83\0\u2eb4\0\u2ee5\0\u2f16\0\u2f47\0\u2f78\0\u2fa9\0\u2fda"+
    "\0\u300b\0\u303c\0\u306d\0\u309e\0\u0126\0\61\0\u30cf\0\u3100"+
    "\0\u3131\0\u3162\0\u3193\0\u0126\0\61\0\61\0\u31c4\0\u31f5"+
    "\0\u3226\0\u3257\0\u3288\0\u32b9\0\u32ea\0\u331b\0\u334c\0\u337d"+
    "\0\61\0\u33ae\0\u33df\0\u3410\0\u3441\0\u3472\0\u34a3\0\u0126"+
    "\0\61\0\u0126\0\61\0\u34d4\0\u3505\0\u3536\0\61\0\u3567"+
    "\0\u3598\0\u35c9\0\u35fa\0\u362b\0\u365c\0\u368d\0\u36be\0\u36ef"+
    "\0\u3720\0\u3751\0\u3782\0\u37b3\0\61";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[341];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\3\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\11\1\14\1\15\1\16\1\11"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\2\11\1\27\1\30\1\11\1\31\1\11\1\32\1\33"+
    "\1\34\1\11\1\35\1\36\1\11\1\37\2\11\1\40"+
    "\1\41\3\2\1\42\1\2\63\0\1\3\56\0\5\43"+
    "\1\44\53\43\6\0\1\45\4\0\1\46\5\0\6\46"+
    "\45\0\1\47\56\0\4\11\3\0\32\11\20\0\1\50"+
    "\1\11\1\13\1\11\3\0\32\11\13\0\1\51\6\0"+
    "\1\52\56\0\4\11\3\0\2\11\1\53\20\11\1\54"+
    "\6\11\20\0\4\11\3\0\1\11\1\55\11\11\1\56"+
    "\2\11\1\57\13\11\20\0\4\11\3\0\16\11\1\60"+
    "\4\11\1\61\3\11\1\62\2\11\20\0\4\11\3\0"+
    "\5\11\1\63\10\11\1\64\1\11\1\65\11\11\20\0"+
    "\4\11\3\0\13\11\1\66\16\11\20\0\4\11\3\0"+
    "\5\11\1\67\10\11\1\70\13\11\20\0\4\11\3\0"+
    "\20\11\1\71\11\11\20\0\4\11\3\0\16\11\1\72"+
    "\13\11\20\0\4\11\3\0\11\11\1\73\20\11\4\0"+
    "\1\74\13\0\4\11\3\0\1\11\1\75\14\11\1\76"+
    "\4\11\1\77\6\11\3\0\1\100\14\0\4\11\3\0"+
    "\17\11\1\101\12\11\20\0\4\11\3\0\5\11\1\102"+
    "\24\11\20\0\4\11\3\0\1\11\1\103\3\11\1\104"+
    "\14\11\1\105\7\11\20\0\4\11\3\0\1\11\1\106"+
    "\3\11\1\107\10\11\1\110\13\11\20\0\4\11\3\0"+
    "\5\11\1\111\24\11\20\0\4\11\3\0\10\11\1\112"+
    "\21\11\20\0\4\11\3\0\5\11\1\113\24\11\30\0"+
    "\1\114\3\0\1\115\14\0\1\116\24\0\1\117\65\0"+
    "\1\46\5\0\6\46\43\0\1\120\1\0\1\47\56\0"+
    "\2\11\1\121\1\11\3\0\32\11\13\0\1\122\2\0"+
    "\1\123\3\0\1\52\56\0\4\11\3\0\11\11\1\124"+
    "\20\11\4\0\1\125\13\0\4\11\3\0\22\11\1\126"+
    "\7\11\20\0\4\11\3\0\3\11\1\127\26\11\20\0"+
    "\4\11\3\0\1\11\1\130\21\11\1\131\6\11\20\0"+
    "\4\11\3\0\20\11\1\132\11\11\20\0\4\11\3\0"+
    "\13\11\1\133\1\11\1\134\14\11\20\0\4\11\3\0"+
    "\20\11\1\135\11\11\20\0\4\11\3\0\1\11\1\136"+
    "\30\11\20\0\4\11\3\0\21\11\1\137\10\11\5\0"+
    "\1\140\12\0\4\11\3\0\22\11\1\141\1\142\6\11"+
    "\20\0\4\11\3\0\16\11\1\143\13\11\20\0\4\11"+
    "\3\0\5\11\1\144\24\11\20\0\4\11\3\0\3\11"+
    "\1\145\26\11\20\0\4\11\3\0\15\11\1\146\14\11"+
    "\20\0\4\11\3\0\1\11\1\147\3\11\1\150\24\11"+
    "\20\0\4\11\3\0\20\11\1\151\11\11\20\0\4\11"+
    "\3\0\15\11\1\152\14\11\44\0\1\153\34\0\4\11"+
    "\3\0\7\11\1\154\22\11\20\0\4\11\3\0\15\11"+
    "\1\155\14\11\20\0\4\11\3\0\13\11\1\156\16\11"+
    "\42\0\1\157\36\0\4\11\3\0\5\11\1\160\24\11"+
    "\20\0\4\11\3\0\4\11\1\161\25\11\20\0\4\11"+
    "\3\0\15\11\1\162\14\11\20\0\4\11\3\0\3\11"+
    "\1\163\7\11\1\164\16\11\20\0\4\11\3\0\27\11"+
    "\1\165\2\11\20\0\4\11\3\0\2\11\1\166\27\11"+
    "\20\0\4\11\3\0\26\11\1\167\3\11\20\0\4\11"+
    "\3\0\22\11\1\170\7\11\20\0\4\11\3\0\20\11"+
    "\1\171\11\11\20\0\4\11\3\0\11\11\1\172\20\11"+
    "\4\0\1\173\13\0\4\11\3\0\13\11\1\174\16\11"+
    "\44\0\1\175\46\0\1\176\7\0\1\177\74\0\1\200"+
    "\24\0\1\201\51\0\1\122\2\0\1\123\55\0\1\123"+
    "\6\0\1\202\56\0\4\11\3\0\5\11\1\203\24\11"+
    "\34\0\1\204\44\0\4\11\3\0\10\11\1\205\21\11"+
    "\20\0\4\11\3\0\12\11\1\206\17\11\6\0\1\207"+
    "\11\0\4\11\3\0\3\11\1\210\26\11\20\0\4\11"+
    "\3\0\5\11\1\161\24\11\20\0\4\11\3\0\4\11"+
    "\1\211\25\11\20\0\4\11\3\0\16\11\1\212\13\11"+
    "\20\0\4\11\3\0\22\11\1\213\7\11\20\0\4\11"+
    "\3\0\21\11\1\214\10\11\5\0\1\215\12\0\4\11"+
    "\3\0\15\11\1\161\14\11\20\0\4\11\3\0\3\11"+
    "\1\216\13\11\1\217\12\11\32\0\1\220\13\0\1\221"+
    "\32\0\4\11\3\0\22\11\1\222\7\11\20\0\4\11"+
    "\3\0\2\11\1\223\27\11\20\0\4\11\3\0\17\11"+
    "\1\224\12\11\20\0\4\11\3\0\14\11\1\225\15\11"+
    "\20\0\4\11\3\0\10\11\1\226\21\11\20\0\4\11"+
    "\3\0\22\11\1\227\7\11\20\0\4\11\3\0\27\11"+
    "\1\161\2\11\20\0\4\11\3\0\5\11\1\136\24\11"+
    "\20\0\4\11\3\0\1\11\1\230\7\11\1\231\20\11"+
    "\4\0\1\232\13\0\4\11\3\0\5\11\1\233\24\11"+
    "\34\0\1\234\44\0\4\11\3\0\5\11\1\235\24\11"+
    "\20\0\4\11\3\0\16\11\1\236\13\11\20\0\4\11"+
    "\3\0\22\11\1\237\7\11\51\0\1\240\27\0\4\11"+
    "\3\0\15\11\1\241\14\11\20\0\4\11\3\0\21\11"+
    "\1\242\10\11\5\0\1\243\12\0\4\11\3\0\22\11"+
    "\1\244\7\11\20\0\4\11\3\0\5\11\1\245\24\11"+
    "\20\0\4\11\3\0\13\11\1\246\16\11\20\0\4\11"+
    "\3\0\13\11\1\247\16\11\20\0\4\11\3\0\22\11"+
    "\1\250\7\11\20\0\4\11\3\0\1\11\1\251\30\11"+
    "\20\0\4\11\3\0\22\11\1\252\7\11\20\0\4\11"+
    "\3\0\22\11\1\131\7\11\51\0\1\253\27\0\4\11"+
    "\3\0\13\11\1\254\16\11\50\0\1\243\15\0\1\243"+
    "\43\0\1\255\43\0\1\256\66\0\1\257\31\0\1\260"+
    "\2\0\1\261\3\0\1\202\56\0\4\11\3\0\20\11"+
    "\1\262\11\11\47\0\1\263\31\0\4\11\3\0\16\11"+
    "\1\264\13\11\20\0\4\11\3\0\7\11\1\265\22\11"+
    "\36\0\1\266\42\0\4\11\3\0\12\11\1\161\17\11"+
    "\6\0\1\267\11\0\4\11\3\0\5\11\1\270\24\11"+
    "\20\0\4\11\3\0\20\11\1\271\11\11\20\0\4\11"+
    "\3\0\5\11\1\272\24\11\20\0\4\11\3\0\11\11"+
    "\1\273\20\11\4\0\1\274\33\0\1\274\24\0\1\274"+
    "\13\0\4\11\3\0\20\11\1\275\11\11\20\0\4\11"+
    "\3\0\13\11\1\276\16\11\47\0\1\277\53\0\1\300"+
    "\36\0\4\11\3\0\5\11\1\301\24\11\20\0\4\11"+
    "\3\0\13\11\1\302\16\11\20\0\4\11\3\0\5\11"+
    "\1\303\24\11\20\0\4\11\3\0\1\11\1\230\30\11"+
    "\13\0\1\304\4\0\4\11\3\0\32\11\20\0\3\11"+
    "\1\305\3\0\32\11\20\0\4\11\3\0\30\11\1\306"+
    "\1\11\57\0\1\307\21\0\4\11\3\0\15\11\1\310"+
    "\14\11\20\0\4\11\3\0\11\11\1\311\20\11\4\0"+
    "\1\312\33\0\1\313\24\0\1\313\13\0\4\11\3\0"+
    "\31\11\1\314\60\0\1\315\20\0\4\11\3\0\11\11"+
    "\1\316\20\11\4\0\1\317\13\0\4\11\3\0\3\11"+
    "\1\320\26\11\20\0\4\11\3\0\5\11\1\321\24\11"+
    "\20\0\4\11\3\0\5\11\1\322\24\11\13\0\1\323"+
    "\4\0\4\11\3\0\32\11\20\0\4\11\3\0\13\11"+
    "\1\324\16\11\20\0\4\11\3\0\11\11\1\325\20\11"+
    "\4\0\1\326\27\0\1\267\44\0\4\11\3\0\16\11"+
    "\1\327\13\11\40\0\1\317\24\0\1\317\25\0\1\330"+
    "\62\0\1\331\37\0\1\260\2\0\1\261\55\0\1\261"+
    "\6\0\1\332\56\0\4\11\3\0\22\11\1\333\7\11"+
    "\51\0\1\334\27\0\4\11\3\0\20\11\1\230\11\11"+
    "\20\0\4\11\3\0\20\11\1\335\11\11\47\0\1\336"+
    "\31\0\4\11\3\0\20\11\1\337\11\11\20\0\4\11"+
    "\3\0\15\11\1\340\14\11\20\0\4\11\3\0\24\11"+
    "\1\341\5\11\53\0\1\342\25\0\4\11\3\0\11\11"+
    "\1\343\20\11\4\0\1\344\13\0\4\11\3\0\5\11"+
    "\1\345\24\11\40\0\1\344\24\0\1\344\27\0\1\346"+
    "\44\0\4\11\3\0\4\11\1\347\25\11\20\0\4\11"+
    "\3\0\5\11\1\350\24\11\20\0\4\11\3\0\15\11"+
    "\1\351\14\11\35\0\1\352\43\0\4\11\3\0\16\11"+
    "\1\353\13\11\45\0\1\354\33\0\4\11\3\0\22\11"+
    "\1\355\7\11\20\0\4\11\3\0\17\11\1\356\12\11"+
    "\46\0\1\357\60\0\1\360\32\0\4\11\3\0\21\11"+
    "\1\361\10\11\5\0\1\362\42\0\1\362\15\0\1\362"+
    "\12\0\4\11\3\0\16\11\1\363\13\11\45\0\1\364"+
    "\33\0\4\11\3\0\3\11\1\365\16\11\1\366\7\11"+
    "\50\0\1\367\15\0\1\367\5\0\1\370\4\0\4\11"+
    "\3\0\32\11\20\0\4\11\3\0\3\11\1\371\26\11"+
    "\32\0\1\372\46\0\4\11\3\0\25\11\1\161\4\11"+
    "\32\0\1\373\16\0\1\374\22\0\1\375\6\0\1\332"+
    "\3\0\1\376\52\0\4\11\3\0\1\11\1\377\30\11"+
    "\30\0\1\u0100\50\0\4\11\3\0\16\11\1\u0101\13\11"+
    "\45\0\1\u0102\33\0\4\11\3\0\22\11\1\u0103\7\11"+
    "\20\0\4\11\3\0\5\11\1\u0104\24\11\34\0\1\u0105"+
    "\44\0\4\11\3\0\17\11\1\u0106\12\11\46\0\1\u0107"+
    "\32\0\4\11\3\0\7\11\1\u0108\22\11\36\0\1\u0109"+
    "\42\0\4\11\3\0\22\11\1\u010a\7\11\30\0\1\u010b"+
    "\50\0\4\11\3\0\15\11\1\u010c\14\11\44\0\1\u010d"+
    "\34\0\4\11\3\0\1\11\1\161\30\11\20\0\4\11"+
    "\3\0\13\11\1\u010e\16\11\42\0\1\u010f\60\0\1\u0110"+
    "\36\0\4\11\3\0\5\11\1\u0111\24\11\34\0\1\u0112"+
    "\44\0\4\11\3\0\15\11\1\u0113\14\11\44\0\1\u0114"+
    "\34\0\4\11\3\0\11\11\1\u0115\20\11\4\0\1\u0116"+
    "\33\0\1\u0117\24\0\1\u0117\26\0\1\u0118\45\0\4\11"+
    "\3\0\1\11\1\u0119\30\11\30\0\1\u011a\70\0\1\u0116"+
    "\24\0\1\u0116\6\0\1\375\12\0\1\376\52\0\4\11"+
    "\3\0\21\11\1\230\10\11\5\0\1\u011b\42\0\1\u011b"+
    "\15\0\1\u011b\12\0\4\11\3\0\23\11\1\u011c\6\11"+
    "\52\0\1\u011d\26\0\4\11\3\0\22\11\1\u011e\7\11"+
    "\51\0\1\u011f\27\0\4\11\3\0\1\11\1\u0120\30\11"+
    "\30\0\1\u0121\73\0\1\u0122\35\0\4\11\3\0\22\11"+
    "\1\u0123\7\11\51\0\1\u0124\27\0\4\11\3\0\5\11"+
    "\1\u0125\24\11\34\0\1\u0126\60\0\1\u0100\44\0\4\11"+
    "\3\0\20\11\1\u0127\11\11\47\0\1\u0128\31\0\4\11"+
    "\3\0\32\11\2\0\1\u0129\60\0\1\u0129\54\0\1\u012a"+
    "\35\0\1\u012b\44\0\4\11\3\0\13\11\1\u012c\16\11"+
    "\42\0\1\u012d\41\0\1\u012e\55\0\4\11\3\0\15\11"+
    "\1\u012f\14\11\44\0\1\u0130\34\0\4\11\3\0\11\11"+
    "\1\u0131\20\11\4\0\1\u0132\33\0\1\u0132\24\0\1\u0132"+
    "\13\0\4\11\3\0\2\11\1\u0133\27\11\31\0\1\360"+
    "\67\0\1\u0134\24\0\1\u0134\13\0\4\11\3\0\1\11"+
    "\1\u0135\30\11\30\0\1\u0136\50\0\4\11\3\0\11\11"+
    "\1\u0137\20\11\4\0\1\u0138\33\0\1\u0138\24\0\1\u0138"+
    "\37\0\1\u011b\50\0\1\u0139\37\0\1\u013a\65\0\4\11"+
    "\3\0\4\11\1\u013b\25\11\33\0\1\u013c\45\0\4\11"+
    "\3\0\16\11\1\u013d\13\11\45\0\1\u0129\33\0\4\11"+
    "\3\0\13\11\1\u013e\16\11\42\0\1\u013f\36\0\4\11"+
    "\3\0\13\11\1\u0140\16\11\42\0\1\u0141\36\0\4\11"+
    "\3\0\6\11\1\u0142\23\11\35\0\1\u0143\71\0\1\u0144"+
    "\1\0\1\u0145\15\0\1\u0145\5\0\1\u0146\4\0\4\11"+
    "\3\0\32\11\13\0\1\u0146\65\0\4\11\3\0\15\11"+
    "\1\230\14\11\20\0\4\11\3\0\5\11\1\377\24\11"+
    "\56\0\1\u0147\51\0\1\u0148\45\0\1\u0149\56\0\1\u014a"+
    "\62\0\1\u014b\56\0\1\u014c\73\0\1\u014d\51\0\1\u014e"+
    "\54\0\1\u014f\70\0\1\u0150\70\0\1\u0151\46\0\1\u0152"+
    "\24\0\1\u0152\40\0\1\u0153\57\0\1\263\61\0\1\u0154"+
    "\62\0\1\u0155\55\0\1\u0110\23\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[14308];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\1\11\5\1\2\11\21\1\2\11"+
    "\1\1\1\0\1\11\1\0\3\1\2\0\21\1\1\0"+
    "\3\1\1\0\13\1\3\0\1\11\1\0\1\1\2\0"+
    "\1\1\1\0\12\1\1\0\12\1\1\0\3\1\1\0"+
    "\13\1\1\0\1\1\4\0\1\1\1\0\1\1\1\0"+
    "\2\1\1\0\5\1\1\0\2\1\2\0\10\1\1\0"+
    "\1\1\1\11\3\1\1\0\2\1\1\0\7\1\1\0"+
    "\1\1\5\0\1\1\1\0\2\1\1\0\1\11\4\1"+
    "\1\0\2\1\2\0\3\1\1\0\2\1\1\0\2\1"+
    "\2\0\1\1\1\0\1\1\1\0\3\1\1\0\2\1"+
    "\1\0\1\1\1\0\1\11\1\0\1\1\1\0\1\1"+
    "\1\0\3\1\1\0\1\1\1\0\1\1\1\0\3\1"+
    "\1\0\1\1\1\0\2\1\2\0\1\1\1\0\1\1"+
    "\1\0\2\1\2\0\1\1\2\0\1\11\1\0\1\11"+
    "\1\1\1\0\1\1\1\0\2\1\1\11\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\2\0"+
    "\1\1\1\0\1\1\1\11\1\1\3\0\1\1\2\0"+
    "\1\1\1\0\1\1\1\0\1\1\2\0\1\1\1\0"+
    "\1\1\1\11\1\1\4\0\1\1\2\11\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\11\1\0\1\1\1\0\2\1\1\0\1\1\1\11"+
    "\1\1\1\11\3\0\1\11\15\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[341];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    // Función para generar los tokens para CUP
    private Symbol symbol(int type) {
        return new Symbol(type, yyline + 1, yycolumn + 1);
    }

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline + 1, yycolumn + 1, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerPKM(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { ManejadorErrores.agregarError(yytext(), yyline + 1, yycolumn + 1, "Léxico PKM", "Símbolo no reconocido en el archivo .pkm");
    return symbol(sym_pkm.error, yytext());
            }
          // fall through
          case 40: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 41: break;
          case 3:
            { return symbol(sym_pkm.COMA, yytext());
            }
          // fall through
          case 42: break;
          case 4:
            { return symbol(sym_pkm.TEXTO_LIBRE, yytext());
            }
          // fall through
          case 43: break;
          case 5:
            { return symbol(sym_pkm.BARRA, yytext());
            }
          // fall through
          case 44: break;
          case 6:
            { return symbol(sym_pkm.NUMERO, yytext());
            }
          // fall through
          case 45: break;
          case 7:
            { return symbol(sym_pkm.MENOR_QUE, yytext());
            }
          // fall through
          case 46: break;
          case 8:
            { return symbol(sym_pkm.IGUAL, yytext());
            }
          // fall through
          case 47: break;
          case 9:
            { return symbol(sym_pkm.MAYOR_QUE, yytext());
            }
          // fall through
          case 48: break;
          case 10:
            { return symbol(sym_pkm.LLAVE_IZQ, yytext());
            }
          // fall through
          case 49: break;
          case 11:
            { return symbol(sym_pkm.LLAVE_DER, yytext());
            }
          // fall through
          case 50: break;
          case 12:
            { // Le quitamos las comillas a la cadena para que pase limpia al parser
        String cadenaLimpia = yytext().substring(1, yytext().length() - 1);
        return symbol(sym_pkm.CADENA, cadenaLimpia);
            }
          // fall through
          case 51: break;
          case 13:
            { return symbol(sym_pkm.HEX_COLOR, yytext());
            }
          // fall through
          case 52: break;
          case 14:
            { return symbol(sym_pkm.HASH_TRES, yytext());
            }
          // fall through
          case 53: break;
          case 15:
            { return symbol(sym_pkm.COLOR_NAME, yytext());
            }
          // fall through
          case 54: break;
          case 16:
            { return symbol(sym_pkm.DROP, yytext());
            }
          // fall through
          case 55: break;
          case 17:
            { return symbol(sym_pkm.LINE, yytext());
            }
          // fall through
          case 56: break;
          case 18:
            { return symbol(sym_pkm.MONO, yytext());
            }
          // fall through
          case 57: break;
          case 19:
            { return symbol(sym_pkm.OPEN, yytext());
            }
          // fall through
          case 58: break;
          case 20:
            { return symbol(sym_pkm.COLOR, yytext());
            }
          // fall through
          case 59: break;
          case 21:
            { return symbol(sym_pkm.META_KEY, yytext());
            }
          // fall through
          case 60: break;
          case 22:
            { return symbol(sym_pkm.STYLE, yytext());
            }
          // fall through
          case 61: break;
          case 23:
            { return symbol(sym_pkm.TABLE, yytext());
            }
          // fall through
          case 62: break;
          case 24:
            { return symbol(sym_pkm.BORDER, yytext());
            }
          // fall through
          case 63: break;
          case 25:
            { return symbol(sym_pkm.DOTTED, yytext());
            }
          // fall through
          case 64: break;
          case 26:
            { return symbol(sym_pkm.DOUBLE_TYPE, yytext());
            }
          // fall through
          case 65: break;
          case 27:
            { return symbol(sym_pkm.SELECT, yytext());
            }
          // fall through
          case 66: break;
          case 28:
            { return symbol(sym_pkm.RGB_COLOR, yytext());
            }
          // fall through
          case 67: break;
          case 29:
            { return symbol(sym_pkm.CONTENT, yytext());
            }
          // fall through
          case 68: break;
          case 30:
            { return symbol(sym_pkm.CURSIVE, yytext());
            }
          // fall through
          case 69: break;
          case 31:
            { return symbol(sym_pkm.ELEMENT, yytext());
            }
          // fall through
          case 70: break;
          case 32:
            { return symbol(sym_pkm.SECTION, yytext());
            }
          // fall through
          case 71: break;
          case 33:
            { return symbol(sym_pkm.MULTIPLE, yytext());
            }
          // fall through
          case 72: break;
          case 34:
            { return symbol(sym_pkm.VERTICAL, yytext());
            }
          // fall through
          case 73: break;
          case 35:
            { return symbol(sym_pkm.TEXT_SIZE, yytext());
            }
          // fall through
          case 74: break;
          case 36:
            { return symbol(sym_pkm.HORIZONTAL, yytext());
            }
          // fall through
          case 75: break;
          case 37:
            { return symbol(sym_pkm.SANS_SERIF, yytext());
            }
          // fall through
          case 76: break;
          case 38:
            { return symbol(sym_pkm.FONT_FAMILY, yytext());
            }
          // fall through
          case 77: break;
          case 39:
            { return symbol(sym_pkm.BG_COLOR, yytext());
            }
          // fall through
          case 78: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
