
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compi1.proyecto1.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HORIZONTAL = 67;
  public static final int SELECT_QUESTION = 7;
  public static final int IDENTIFICADOR = 82;
  public static final int TEXT_SIZE = 71;
  public static final int MENOR_IGUAL = 35;
  public static final int COLOR_WHITE = 25;
  public static final int CORCHETE_DER = 44;
  public static final int TABLE = 3;
  public static final int TIPO_STRING = 10;
  public static final int COLOR_BLACK = 24;
  public static final int LLAVE_IZQ = 45;
  public static final int COLOR_HEX = 79;
  public static final int POTENCIA = 30;
  public static final int MAYOR = 32;
  public static final int COLOR_PURPLE = 21;
  public static final int ERROR_LEXICO = 83;
  public static final int SANS_SERIF = 74;
  public static final int DROP_QUESTION = 6;
  public static final int DIFERENTE = 37;
  public static final int ELEMENTS = 59;
  public static final int PAR_DER = 42;
  public static final int OPEN_QUESTION = 5;
  public static final int POR = 28;
  public static final int NUMERO = 80;
  public static final int DOUBLE = 78;
  public static final int BACKGROUND_COLOR = 69;
  public static final int NOT = 40;
  public static final int TEXT = 4;
  public static final int DOS_PUNTOS = 48;
  public static final int WIDTH = 54;
  public static final int PUNTO_COMA = 53;
  public static final int IGUALDAD = 36;
  public static final int STYLES = 60;
  public static final int DIVIDIDO = 29;
  public static final int COMA = 47;
  public static final int MODULO = 31;
  public static final int CURSIVE = 75;
  public static final int MONO = 73;
  public static final int WHILE = 14;
  public static final int CORCHETE_IZQ = 43;
  public static final int DO = 15;
  public static final int FOR = 16;
  public static final int COMODIN = 52;
  public static final int ORIENTATION = 58;
  public static final int ELSE = 13;
  public static final int MENOS = 27;
  public static final int MULTIPLE_QUESTION = 8;
  public static final int MENOR = 34;
  public static final int MAS = 26;
  public static final int TIPO_NUMBER = 9;
  public static final int CORRECT = 64;
  public static final int CONTENT = 61;
  public static final int PAR_IZQ = 41;
  public static final int EOF = 0;
  public static final int PUNTO = 50;
  public static final int VERTICAL = 66;
  public static final int LLAVE_DER = 46;
  public static final int LINE = 76;
  public static final int LABEL = 62;
  public static final int IN = 17;
  public static final int OR = 38;
  public static final int error = 1;
  public static final int IF = 12;
  public static final int TIPO_SPECIAL = 11;
  public static final int DOTTED = 77;
  public static final int COLOR = 68;
  public static final int COLOR_SKY = 22;
  public static final int COLOR_GREEN = 20;
  public static final int BORDER = 72;
  public static final int HEIGHT = 55;
  public static final int RANGO = 51;
  public static final int ASIGNACION = 49;
  public static final int CADENA = 81;
  public static final int FONT_FAMILY = 70;
  public static final int COLOR_RED = 18;
  public static final int POINTY = 57;
  public static final int OPTIONS = 63;
  public static final int POINTX = 56;
  public static final int AND = 39;
  public static final int COLOR_BLUE = 19;
  public static final int COLOR_YELLOW = 23;
  public static final int WHO_IS_THAT_POKEMON = 65;
  public static final int MAYOR_IGUAL = 33;
  public static final int SECTION = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SECTION",
  "TABLE",
  "TEXT",
  "OPEN_QUESTION",
  "DROP_QUESTION",
  "SELECT_QUESTION",
  "MULTIPLE_QUESTION",
  "TIPO_NUMBER",
  "TIPO_STRING",
  "TIPO_SPECIAL",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "IN",
  "COLOR_RED",
  "COLOR_BLUE",
  "COLOR_GREEN",
  "COLOR_PURPLE",
  "COLOR_SKY",
  "COLOR_YELLOW",
  "COLOR_BLACK",
  "COLOR_WHITE",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "POTENCIA",
  "MODULO",
  "MAYOR",
  "MAYOR_IGUAL",
  "MENOR",
  "MENOR_IGUAL",
  "IGUALDAD",
  "DIFERENTE",
  "OR",
  "AND",
  "NOT",
  "PAR_IZQ",
  "PAR_DER",
  "CORCHETE_IZQ",
  "CORCHETE_DER",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "COMA",
  "DOS_PUNTOS",
  "ASIGNACION",
  "PUNTO",
  "RANGO",
  "COMODIN",
  "PUNTO_COMA",
  "WIDTH",
  "HEIGHT",
  "POINTX",
  "POINTY",
  "ORIENTATION",
  "ELEMENTS",
  "STYLES",
  "CONTENT",
  "LABEL",
  "OPTIONS",
  "CORRECT",
  "WHO_IS_THAT_POKEMON",
  "VERTICAL",
  "HORIZONTAL",
  "COLOR",
  "BACKGROUND_COLOR",
  "FONT_FAMILY",
  "TEXT_SIZE",
  "BORDER",
  "MONO",
  "SANS_SERIF",
  "CURSIVE",
  "LINE",
  "DOTTED",
  "DOUBLE",
  "COLOR_HEX",
  "NUMERO",
  "CADENA",
  "IDENTIFICADOR",
  "ERROR_LEXICO"
  };
}

